### ISSUE TITLE
updateRandomLetters in Dictionary

### ISSUE THREAD

**Issue by Jelleas** [BartvonMeijenfeldt/Ghost#7]
What is this? I don't even....

How can this even work?

```
do {
    word_random = dict.getRandomWord();
} while (word_random.length() < letters + 1);
```

So the above is a hack to get a random word with length < letters, and letters as the name does not imply is an integer???

Followed by:

```
for(int i = 0; i < letters; i++) {
    this.guess(word_random.charAt(i));
```

But... if word_random.length < letter + 1, then this can give an out of bounds exception at some point.

**Comment by new-username123** [comment]
ik krijg hiermee juist een woord dat groter of gelijk is aan letters + 1, ik heb nu ook commentaar toegevoegd
