### ISSUE TITLE
10 instance variables in ChoosePlayersActivity.java

### ISSUE THREAD

**Issue by Jelleas** [BartvonMeijenfeldt/Ghost#8]
Why????!!!!!!

**Comment by Jelleas** [comment]
Activities seem to have tons of instance variables

**Comment by stgm** [comment]
Hee @Jelleas, we kunnen er maar één vinden die niet in meerdere methods wordt gebruikt. Bedoel je nog iets anders?

**Comment by Jelleas** [comment]
ChoosePlayersActivity is waarschijnlijk een slecht voorbeeld, GameActivity komt wat meer over. 

Maar toch, waarom alle views opslaan als instance variables als je ze ook kan terug vinden wanneer je ze nodig hebt? Plus, je kan deze code zo refactoren dat alle views niet zowel in onCreate als in één of andere onClick methode word gebruikt (heb je meteen alle duplicate code binnen de class ChoosePlayersAcitivity eruit).

**Comment by new-username123** [comment]
nu nog 4 instance variables in die klasse, heb de code gerefactored om zoveel mogelijk duplicate code eruit te gooien
